### ISSUE TITLE
Streaming support using JSNIRF

### ISSUE THREAD

**Issue by fangq** [NeuroJSON/jsnirf#1]
@samuelpowell, just to follow up the discussion on data streaming in https://github.com/fNIRS/snirf/issues/103#issuecomment-1066143467, here are a few thoughts

1. JSON supports data streaming in multiple ways - JSON array or object does not specify length, so you can simply append more elements before closing it with `]` or `}`, so it is inherently streaming friendly
2. JSON also support [dataset level streaming](https://en.wikipedia.org/wiki/JSON_streaming) via various line/white-space/newline (NDJSON) delimited JSON root-objects; this has been extensively used in many web/db applications. Such construct is already supported as JSNIRF (based on [JData annotations](https://github.com/NeuroJSON/jdata/blob/master/JData_specification.md#text-based-jdata-storage-grammar)) explicitly permit [concatenated JSON objects](https://github.com/NeuroJSON/jsnirf/blob/master/JSNIRF_specification.md#grammar).
3. BJData - the binary interface of JSON in JSNIRF - is slightly extended from the widely supported UBJSON and supports [streaming naively](https://en.wikipedia.org/wiki/UBJSON#Rationale_and_Objectives). Both UBJSON and BJData even have a built-in marker `N` for `no-op` to keep [connection alive](https://ubjson.org/type-reference/value-types/#noop), specifically designed for data streaming (UBJSON was motivated as the binary format for [CouchDB](https://github.com/apache/couchdb/issues/2203#issuecomment-754224498) and some of these designs were really tailed and well-suited for such purpose).
4. both JSON (via [JSON-LD](https://json-ld.org/) or [JSON-reference](https://json-spec.readthedocs.io/reference.html)) and JData  (via [`_DataLink_`](https://github.com/NeuroJSON/jdata/blob/master/JData_specification.md#data-referencing-and-links)) support data linking/referencing. tags such as `"$ref":"UUID"` can be added at the any level of the JSON tree to create linked data records stored in a different file/section/url. The only issue is that my current MATLAB/Python implementations of JData spec do not support retrieving these records, yet.

overall, JSON has a much much bigger ecosystem than HDF5, there are solutions/specs/libraries to almost any issue we could possibly encounter for fnirs data storage/exchange. The goal of the NeuroJSON project is to simply take advantage of such ecosystem and existing resources, such as data validation using [JSON Schema](https://json-schema.org/), database using [NoSQL](https://www.mongodb.com/nosql-explained) db, linking via JSON-LD etc, and make data scalable, portable, searchable/findable, and universally parsable.

Currently, almost every neuroimaging community is migrating towards BIDS, SNIRF spec is also co-evolving with influences from BIDS. As part of the NeuroJSON project, I am currently working with @robertoostenveld, who is also a main contributor to BIDS, to map the entire BIDS data tree to a JSON tree so we can port everything to a database. It may take a while for the community to see buy-in, but ultimately I hope the simplicity and the scalability (using NoSQL db) could convince everyone this is a viable path.

**Comment by samuelpowell** [comment]
Hi @fangq thank you for your detailed response.

I understand your points, and how from a technical perspective this could be a compelling solution which enables/simplifies the implementation of various use cases. I will continue to keep my eye on developments and we will look to provide support as the ecosystem develops. Note that just because we might not choose to ship something doesn't mean that we don't actively evaluate different approaches internally - there will always be a bit of a lag between the bleeding edge and production - for the usual reasons.

Digging into the details a bit more:

1. Sure. So you're saying we'd dump an array of channel data into the the containing `dataTimeSeries` array as it is generated. When complete we'd terminate the array or arrays. The problem is that we have various different auxiliary data streams, we'd have to record each to disk (we can't keep it all in memory) and then build the output file when we terminate. This is messy.
2. This sounds good, see below.
3. The problem at hand is more about streaming data from instrument to disk than over a network connection (we have different methods for that), but will keep this in mind.
4. This looks more like a way of referencing other complete fields, rather than concatenation, which is my current concern, or have I misunderstood?

Point (2) looks like a good solution to me. I don't know much about this but thought that concatenated JSON was more about adding new objects to the tree, rather than extending existing objects. Obviously that's no issue in a new format as you can simply add a new object which you understand to explicitly represent, e.g., a new block of time-series data - but I couldn't see from the JSNIRF spec the format we would use to indicate concatenation of a given array.

So to be clear, are you saying that in the current specification we could write out the current root object containing fixed metadata, then add additional _root_ objects which extend the appropriate time-series row-by-row, or column-by-column? This approach wasn't clear to me from the specification, but I understand that the example was written out to look like SNIRF. If my understanding is correct could you give a brief example of what this would look like, or point me in the direction of the documentation?

**Comment by fangq** [comment]
> Point (2) looks like a good solution to me. I don't know much about this but thought that concatenated JSON was more about adding new objects to the tree, rather than extending existing objects. Obviously that's no issue in a new format as you can simply add a new object which you understand to explicitly represent, e.g., a new block of time-series data - but I couldn't see from the JSNIRF spec the format we would use to indicate concatenation of a given array.

Semantically, it is not explicitly required that records in a concatenated JSON (or NDJSON) document must be connected, however, they have been the dominant format for JSON-based streaming, implying that data in each record represent chunks from a continuous data feed.

If a semantic connection is desired between concatenated data records, or even between multiple files, the optional DICOM-inspired [`metaDataTag.{AccessionNumber,InstanceNumber}`](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#:~:text=tag%20%22Accession%20Number%22(-,0008%2C0050,-)%2C%20as%20defined%20in) fields to connect multiple JSNIRF blocks. The meanings of these DICOM header fields can be found here

- `AccessionNumber`: [(0008,0050)](https://dicom.innolitics.com/ciods/enhanced-sr/general-study/00080050)
- `InstanceNumber`: [(0020,0013)](https://dicom.innolitics.com/ciods/mr-image/general-image/00200013), or in your case,
- `AcquisitionNumber`: [(0020,0012)](https://dicom.innolitics.com/ciods/mr-image/general-image/00200012)

I [added those in SNIRF](https://github.com/fNIRS/snirf/commit/cc8d83bd108489e03bd7f2a4b3feafa3d9e63db2#diff-a6c853dca5f1a8eb3e37e0de75889250190b68f3597e91f33489a05874aa49c4R218-R227) back in the days to address something like this. I want to mention that using `metaDataTag` to define data sequences is applicable to both HDF5-based SNIRF file, and JSON based JSNIRF records.

Dynamically expand data record by taking advantage of HDF5 feature is certain a smart approach, but either JSON or `metaDataTag` can serve as more portable workarounds. The JSON approach will come in handy when streaming over the cloud (with a db backend or in a web client, for example).

**Comment by samuelpowell** [comment]
Okay I can see how this would be useful to link together files from related experiments, or larger individual blocks of data. But I'm still not exactly sure what you're proposing for frame by frame recording.

Here is the [simple_probe.jnirs](https://github.com/fNIRS/snirf-samples/blob/00f31b259659d1f576ec36c2afa5a5eb23fe5ad3/basic/Simple_Probe.jnirs) file from your repository, with the actually data removed:

```json
{
	"SNIRFData": {
		"formatVersion": "1.0",
		"metaDataTags": {
			"SubjectID": "default",
			"MeasurementDate": "2020-05-16",
			"MeasurementTime": "17:05:44",
			"LengthUnit": "cm",
			"TimeUnit": "s",
			"FrequencyUnit": "Hz"
		},
		"data": {
			"dataTimeSeries": {
				"_ArrayType_": "double",
				"_ArraySize_": [1200,8],
				"_ArrayZipSize_": [1,9600],
				"_ArrayZipType_": "zlib",
				"_ArrayZipData_":  "REMOVED"
			},
			"measurementList": {
				"dataType": [1,1,1,1,1,1,1,1],
				"dataTypeIndex": [0,0,0,0,0,0,0,0],
				"detectorGain": [0,0,0,0,0,0,0,0],
				"detectorIndex": [1,2,3,4,1,2,3,4],
				"moduleIndex": [0,0,0,0,0,0,0,0],
				"sourceIndex": [1,1,1,1,1,1,1,1],
				"sourcePower": [0,0,0,0,0,0,0,0],
				"wavelengthIndex": [1,1,1,1,2,2,2,2]
			},
			"time": {
				"_ArrayType_": "double",
				"_ArraySize_": [1200,1],
				"_ArrayZipSize_": [1,1200],
				"_ArrayZipType_": "zlib",
				"_ArrayZipData_": "REMOVED" 
			}
		},
		"probe": {
			"correlationTimeDelay": 0,
			"correlationTimeDelayWidth": 0,
			"detectorLabels": [
				"D1",
				"D2",
				"D3",
				"D4"
			],
			"frequency": 70000000,
			"sourceLabels": "S1",
			"timeDelay": 0,
			"timeDelayWidth": 0,
			"wavelengths": [690,830],
			"detectorPos2D": [
				[0,0],
				[4,0],
				[0,4],
				[4,4]
			],
			"sourcePos2D": [2,2]
		},
		"stim": [
			{
				"data": [
					[30.7,5,1],
					[65.2,5,1]
				],
				"name": "1"
			},
			{
				"data": [50.2,5,1],
				"name": "3"
			},
			{
				"data": [23.7,5,1],
				"name": [
					"3",
					""
				]
			}
		],
		"aux": {
			"dataTimeSeries": {
				"_ArrayType_": "double",
				"_ArraySize_": [1200,1],
				"_ArrayZipSize_": [1,1200],
				"_ArrayZipType_": "zlib",
				"_ArrayZipData_": "REMOVED"
			},
			"name": "aux1",
			"time": {
				"_ArrayType_": "double",
				"_ArraySize_": [1200,1],
				"_ArrayZipSize_": [1,1200],
				"_ArrayZipType_": "zlib",
				"_ArrayZipData_":  "REMOVED"
			},
			"timeOffset": 0
		}
	}
}

```

This contains measurements of eight channels, and some auxiliary data, over 1200 time points.  

Suppose now I wish to append the 1201st time point to both the channel data and the auxiliary data, by appending to the file, not changing its existing contents.

Can you provide an example of how this would look, which is conformant to your spec?

**Comment by fangq** [comment]
you could append data without using concatenated JSON by
```json
{
  "SNIRFData": [
    {
        "formatVersion": "1.0",
        "metaDataTags": {
	    "SubjectID": "default",
	    ...
	    "AcquisitionNumber": 1
	},
       "data": {
           "dataTimeSeries": {...},
           "measurementList": {...}
           "time": {...}
       },
       "probe": {...},
       "stim": {...},
       "aux": {
           "dataTimeSeries": {...},
           "name":"",
           "time": {...}
       }
    },
    {
        "formatVersion": "1.0",
        "metaDataTags": {
	    "SubjectID": "default",
	    ...
	    "AcquisitionNumber": 2
	},
       "data": {
           "dataTimeSeries": {...appended data...},
           "measurementList": {...appended data...},
           "time": {...appended data...}
       },
       "probe": {...},
       "stim": {...},
       "aux": {
           "dataTimeSeries": {...appended data...},
           "name":"",
           "time": {...appended data...}
       }
    },
    ...
  ]
}
```

or wrap each sub-element in the above `SNIRFData` array object into a separate SNIRFData object in a concatenated JSON
```json
{
  "SNIRFData": {
        "formatVersion": "1.0",
        "metaDataTags": {
	    ...
	    "AcquisitionNumber": 1
        },
       ...
  }
}
{
  "SNIRFData": {
        "formatVersion": "1.0",
        "metaDataTags": {
	    ...
	    "AcquisitionNumber": 2
        },
       ...
  }
}

```

The only downside is that there might have some redundancy for `probe/stim/metaDataTag` sections.

Another possibility is that we can expand JSNIRF to specifically accept streaming data increments in the form of additional concatenated JSON objects and merge it with the first chunk in the parser. I do not have this fully outlined, but we could potentially do something like

```json
{"SNIRFData":{initial data}}
{"SNIRFData":{...,"metaDataTag":{...,"AppendMode":true,}, additional data only for fields that have increments }
...
```

if we don't want to reinvent wheels, [JSON Patch](http://jsonpatch.com/) is another way to do this - and it is supported by a number of libraries, including the [JSON for Modern C++](https://github.com/nlohmann/json/blob/develop/test/src/unit-merge_patch.cpp) library.

**Comment by samuelpowell** [comment]
Thanks @fangq, to be clear I'm not talking about new acquisitions with new metadata. I'm talking about a single acquisition where only the size of the time series arrays needs to grow by appending to the file, not modifying the previously written contents.

From the discuss above it feels as though this will not fit easily within the existing specification. I don't want to push too hard on this because obviously you have specific goals for JSNIRF which might end up watered down and overcomplicated in order to meet this particular use case.

Happy to leave this issue open if you want to consider further in the future, and we will certainly look at support for JSNIRF as an exported format, where none of these problems exist as the entire time series is available.

**Comment by fangq** [comment]
@samuelpowell, no worries at all. 

All I am doing here is to document some of the thoughts/discussions related to data streaming and will flush out these in more details with our newly established steering committee, hopefully we will make something more concrete down the path.

Closing this for now.

**Comment by samuelpowell** [comment]
Okay, please don't hesitate to get in touch if you want to discuss further, and thanks again for looking at options here.
